# Generated by Django 3.2 on 2021-04-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=70)),
                ('item', models.CharField(max_length=70)),
                ('quantity', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='', verbose_name='cartimg/')),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'cartlist',
            },
        ),
        migrations.CreateModel(
            name='productlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=70)),
                ('item', models.CharField(max_length=70)),
                ('quantity', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='', verbose_name='media/')),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'productlist',
            },
        ),
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=70)),
                ('Last_name', models.CharField(max_length=70)),
                ('Email_Id', models.EmailField(max_length=70)),
                ('Phone_Number', models.IntegerField()),
                ('username', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('Confirm_Password', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'Reg',
            },
        ),
    ]
